CREATE TABLE buyer_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company TEXT NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    product TEXT,
    quantity TEXT,
    location TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE farmer_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    village TEXT,
    district TEXT,
    state TEXT,
    crop TEXT,
    quantity NUMERIC,
    delivery_date DATE,
    price TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE nt_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    img TEXT,
    tag TEXT,
    desc_text TEXT,
    is_mock BOOLEAN DEFAULT false,
    loaded BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE nt_crop_prices (
    crop_id TEXT PRIMARY KEY,
    price TEXT NOT NULL,
    trend TEXT NOT NULL
);

-- Insert some dummy data for products
INSERT INTO nt_products (title, category, img, tag, desc_text) VALUES 
('Premium Basmati Rice', 'Grains', 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80', 'Export Grade', 'Aged for 24 months, extra long grain basmati rice perfect for biryani and premium dishes. Double polished and sorted.'),
('Organic Turmeric Fingers', 'Spices', 'https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=600&q=80', 'High Curcumin', 'Sun-dried organic turmeric with 5%+ curcumin content. Sourced directly from Erode and Nizamabad farms.'),
('Green Mung Beans', 'Pulses', 'https://images.unsplash.com/photo-1515543582370-4cff31e54e8b?auto=format&fit=crop&w=600&q=80', 'Fresh Harvest', 'Premium quality, unpolished green mung beans rich in protein. Mechanically cleaned and sorted.');

-- Insert some dummy data for prices
INSERT INTO nt_crop_prices (crop_id, price, trend) VALUES
('basmati', '₹58,000', '+4%'),
('turmeric', '₹94,000', '+7%'),
('mung', '₹72,000', '-2%'),
('lentils', '₹64,000', '+1%');
